### ISSUE TITLE
Disable Deflicker Filter

### ISSUE THREAD

**Issue by devlman127** [GaryOderNichts/evwii#10] opened 2024-06-04 03:55 UTC
I know that USB Loader GX has a feature to fix the smoothing caused by deflicker but the problem is that it only applies to games launched through it, which is a shame if you prefer vWii channels, Wii U injects, or using physical discs. Is it possible to implement this feature with this plugin?

**Comment by GaryOderNichts** [comment] 2024-06-04 15:41
Duplicate of #4.
TL;DR: Not possible without applying patches to the individual games.

**Closed as not planned by GaryOderNichts** 2024-06-04 15:41 UTC

**Comment by devlman127** [comment] 2024-06-10 04:21
The deflicker filter setting is in the loader settings instead of individual games and is able to do so automatically. How do they do it, and could this do the same?
